---
- name: Setup vprofile Bastion host
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Import Vpc setup variable
      include_vars: vars/bastion_setup

    - name: Import Vpc setup variable
      include_vars: vars/vpc-var
 # To Create security group
    - name: Create vprofile ec2 key
      ec2_key:
        name: vprofile-key
        region: "{{region}}"
      register: key_out
  # To save the private key into bastion-key.pem
    - name: Save private key into file bastion-key.pem
      copy:
        content: "{{key_out.private_key}}"
        dest: "./bastion-key.pem"
        mode: 0600
      when: key_out.changed  

    - name: Create sec Grp for bastion host
      ec2_group:
        name: Bastion-host-sg
        description: Allow port 22 from everywhere and all port within sg
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{MYIP}}"
        register: BastionSG_out

    - Creating Bastion Host
      ec2:
        key_name: vprofile-key
        region: "{{region}}"
        instance_type: t2.micro
        image: "{{ bastion_ami}}"
        wait: yes
        wait_timeout: 300
        instance_tags:
          Name: "Bastion_host"
          project: vprofile
          owner: DevOps Team
        exact_count: 1
        count_tag:
          Name : "Bastion_host"
          Project: vprofile
          owner: DevOps Team
        group_id: "{{BastionSG_out.group_id}}"
      register: Bastion_out   
