- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC variables
      include_vars: vars/vpc-var

    - name: Create vprofile vpc
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        region: "{{region}}"
        dns_hostnames: yes
        tenancy: default
        state: "'{{state}}"
      # this is to store the output
      register: vpcout
    # using debug to module to print the out stored in register
    - debug:
        var: vpout

    - name: create public subnet 1 in zone1
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone 1}}"
        state: "{{state}}"
        cidr: "{{pubsub1Cidr}}"
        map_public: yes
        resource_tags:
          name: vprofile-pubsub1
      register: pubsub1_out