- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC variables
      include_vars: vars/vpc-var

    - name: Create vprofile vpc
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        region: "{{region}}"
        dns_hostnames: yes
        tenancy: default
        state: "'{{state}}"
      # this is to store the output
      register: vpcout
    # using debug to module to print the output stored in register
    #- debug:
     #   var: vpout

    - name: create public subnet 1 in zone1
      ec2_vpc_subnet:
        vpc_id: "{{ vpcout.vpc.id}}"
        region: "{{ region}}"
        az: "{{ zone1}}"
        state: "{{ state}}"
        cidr: "{{ pubsub1Cidr}}"
        map_public: yes
        resource_tags:
          Name: vprofile-pubsub1
      register: pubsub1_out

    - name: create public subnet 2 in zone2
      ec2_vpc_subnet:
        vpc_id: "{{ vpcout.vpc.id}}"
        region: "{{ region}}"
        az: "{{ zone2}}"
        state: "{{ state}}"
        cidr: "{{ pubsub2Cidr}}"
        map_public: yes
        resource_tags:
          Name: vprofile-pubsub2
      register: pubsub2_out

    - name: create public subnet 3 in zone3
      ec2_vpc_subnet:
        vpc_id: "{{ vpcout.vpc.id}}"
        region: "{{ region}}"
        az: "{{ zone3}}"
        state: "{{ state}}"
        cidr: "{{ pubsub3Cidr}}"
        map_public: yes
        resource_tags:
          Name: vprofile-pubsub3
      register: pubsub3_out

    - name: create private subnet 1 in zone1
      ec2_vpc_subnet:
        vpc_id: "{{ vpcout.vpc.id}}"
        region: "{{ region}}"
        az: "{{ zone1}}"
        state: "{{ state}}"
        cidr: "{{ privsub1Cidr}}"
        map_public: yes
        resource_tags:
          Name: vprofile-privsub1
      register: privsub1_out

    - name: create private subnet 2 in zone2
      ec2_vpc_subnet:
        vpc_id: "{{ vpcout.vpc.id}}"
        region: "{{ region}}"
        az: "{{ zone2}}"
        state: "{{ state}}"
        cidr: "{{ privsub1Cidr}}"
        map_public: yes
        resource_tags:
          Name: vprofile-privsub2
      register: privsub2_out

      - name: create private subnet 3 in zone3
      ec2_vpc_subnet:
        vpc_id: "{{ vpcout.vpc.id}}"
        region: "{{ region}}"
        az: "{{ zone3}}"
        state: "{{ state}}"
        cidr: "{{ privsub3Cidr}}"
        map_public: yes
        resource_tags:
          Name: vprofile-privsub3
      register: privsub3_out

    - name: Internet Gateway Setup
      ec2_vpc_igw:
        vpc_id: "{{ vpcout.vpc.id}}"
        region: "{{ region}}"
        state: "{{ state}}"
        resource_tags:
          Name: vprofile-IGW
      register: igw_out

    - name: Set up public subnet route table
      ec2_vpc_route_table:
        vpc_id: "{{ vpcout.vpc.id}}"
        region: "{{ region}}"
        tags:
          Name: vprofile-pubRT
        subnets:
          - "{{pubsub1_out.subnet.id}}"
          - "{{pubsub2_out.subnet.id}}"
          - "{{pubsub3_out.subnet.id}}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{igw_out.gateway_id}}"
      register: pubRT_out